### ISSUE TITLE
Error when trying to open CEA Dashboard [cont.]

### ISSUE THREAD

**Issue by fcschuch** [architecture-building-systems/CityEnergyAnalyst#2798]
@daren-thomas I submitted this issue last year (issue #2457) and you helped me with it, sorry I did not follow up back then.
I have now installed CEA again, but the issue still persists (same error message when I open the Dashboard).

I made sure to install CEA in the Documents folder this time, and tried running 'cea dashboard' in the console, getting the following output:

Could it be an issue with my machine?

![image](https://user-images.githubusercontent.com/57716103/86216881-0e9ce900-bb55-11ea-9c62-5dfdad413361.png)

**Comment by daren-thomas** [comment]
@fcschuch that's the expected behavoir - you've just started the server part of the CEA. What you _should_ be doing is running the GUI - check your start menu for a "CEA Dashboard" link. _or_ in the folder `C:\Users\Administrator\Documents\CityEnergyAnalyst` you should find that shortcut too.

**Comment by daren-thomas** [comment]
(please note that manually running `cea dashboard` is not required - the GUI starts the server on startup)

**Comment by fcschuch** [comment]
@daren-thomas the problem is I haven't been able to open the cea dashboard shortcut. I get the following error message:

![image](https://user-images.githubusercontent.com/57716103/86305714-b7e0ef00-bbe8-11ea-9f67-7c7ef3bd5d2a.png)

**Comment by daren-thomas** [comment]
@fcschuch what version of Windows are you using?

**Comment by fcschuch** [comment]
@daren-thomas Windows 7

**Comment by daren-thomas** [comment]
@fcschuch unfortunately, we don't have a windows 7 machine to test on. @reyery will try to test it on a virtual machine to see if he can reproduce the error.

**Comment by reyery** [comment]
After trying a installation of CEA on a fresh Windows 7 machine I can confirm that it still works on Windows 10.
Examining the error that you provided again, It seems that maybe the GUI was not able to run **cmd.exe** and spawn a new process. 

@fcschuch Could you help me check if you are able to run **cmd.exe** manually and if it is in your `PATH` environment variable? 
- Search for "run" in the search bar of the start menu in Windows then type "cmd" in the input and press Ok. You should be able to open the command prompt. 
- Search for "Edit environment variables for your account" in the search bar of the start menu in Windows and check if `C:\Windows\system32` is in `PATH` of system variables.

**Comment by fcschuch** [comment]
@reyery many thanks.
I took the steps above and was able to open the cmd (image below). I also checked the "Edit environment variables for your account" and this is what appears for the PATH: 
C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\;C:\Python36;C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;C:\Users\Administrator\AppData\Local\atom\bin

![image](https://user-images.githubusercontent.com/57716103/87275197-07120400-c4b4-11ea-84f3-ce2fca466eb6.png)

**Comment by reyery** [comment]
Alright, I think `C:\Windows\System32` not being in `PATH` might be the problem. Would you mind appending it to the `PATH` variable and try launching CEA again?

**Comment by fcschuch** [comment]
@reyery Yes, that worked! Thank you very much

**Comment by reyery** [comment]
@fcschuch no worries, glad to be of help! Feel free to open a new issue if you encounter any more problems.

Closing this issue as it is solved.

**Comment by noivoindio** [comment]
@reyery Hi! I think I have a similar error but I can't solve it. I have CEA version 3.7.0 in Windows 10 and when I start CEA dashboard, it appears these similar errors. I already reinstall the program but the error remains. After these errors, the program closes. I don't know what I'm doing wrong.

I hope that you can help me with this. Thank you in advance.


![image1](https://user-images.githubusercontent.com/69899773/90626607-1d2d8580-e213-11ea-82f2-6257ecd7d5db.jpeg)
![image2](https://user-images.githubusercontent.com/69899773/90626611-1e5eb280-e213-11ea-978a-56a5f49ca829.jpeg)
