### ISSUE TITLE
Rename `cea/utilities/helpers.py` and document CEA code standards for times

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#388]
The file `cea/utilities/helpers.py` contains a list of functions to convert to and from the "Hour Of Year" and "Seasonhours" convention as well as similar functions for such time computings.

"helpers" is a very generic name. We could come up with something better. "timeconversions"? Or "time_helpers"? I suggest "`hour_of_year.py`"

Also, this module should include a docstring at the top explaining:

- what the different time representations are (hoy, seasonhours)
- what their default variable name in code is (`hoy`, `seasonhour`)
- which one is referred to when we see `t`
- how to handle southern hemisphere logic (seasonhours starts at the heating season, which, as far as I can tell from the code is assumed to be sometime after august, but, say, New Zealand or South Africa would start heating sometime in May instead)

This documentations and discussion should also be reflected somehow in the dev manual.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA thoughts?

**Comment by JIMENOFONSECA** [comment]
for 'season hours', it should be solved with #251.
for 'hoy', @gabriel-happle could you comment on this?

**Comment by gabriel-happle** [comment]
`hoy` is my variable name for 'hour of the year'. i.e. `hoy = 1` first hour on 1st of January.
`seasonhour` is my variable name for 'hour of the season'. i.e. `seasonhour = 1` is the first hour at the start of the heating season.
`t` is now the same as `seasonhour`. so it is used for counting the hours in the for loop. `hoy` is e.g. used to look up data from the weather file, or similar. For any location the conversion from `hoy` to `seasonhour` is obviously different. But this has all been prepared in the `helpers.py`.
Please go on with changing names of functions and variables.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas is this solved?

**Comment by daren-thomas** [comment]
No, it is not solved. I was waiting for the @gabriel-happle branch to be merged before looking into this again. We need to talk.

I am worried about the use of `hoy` in the code as sometimes we move back to `t`. We should write up a clear explanation of this.

**Comment by daren-thomas** [comment]
This is tied to #251 - basically, we can remove the notion of "seasonhours" and also remove the helpers module with the implementation of #251

**Comment by daren-thomas** [comment]
fixed, the whole module has been deleted.
